### ISSUE TITLE
Remove number-input spinner decoration in Firefox

### ISSUE THREAD

**Issue by thegoldgoat** [vantezzen/blymp-io#1]
I can see the spinner is not shown in Chrome/Safari, but it is visible in Firefox.

Here is an example of 2 fixed inputs and 2 not fixed yet:

![immagine](https://user-images.githubusercontent.com/25644731/103802320-411d2680-504f-11eb-9f64-db28514e85f7.png)

In order to achieve this, I had to apply this style to those inputs:

` -moz-appearance: textfield;`

One can apply it to every number input, like this:

```
input[type='number'] {
  -moz-appearance: textfield;
}
```

**Comment by vantezzen** [comment]
Thank you for the report! I just published a new commit that should fix this problem.
