### ISSUE TITLE
Do you have any plans to support self-hosting via docker?

### ISSUE THREAD

**Issue by ovizii** [vantezzen/blymp-io#5]
I'm quite curious to give blymp-io a spin but I wouldn't want to reinvent the wheel so if anyone has already published a docker-compose.yml file that would be great.

**Comment by vantezzen** [comment]
I haven't created a docker-compose.yml or DOCKERFILE myself yet but I would guess that it should be really easy to do so:

blymp-io doesn't require a Database, Redis etc. so it should just be using a NodeJS container with this code, `npm install`, `npm run build` and `npm start` to get it up and running.

If you decide to set up a docker-compose.yml yourself, I would be happy to add it into this repo so others can profit from it!

**Comment by ovizii** [comment]
I'll give it a try and post my results or errors here, maybe somebody can add something to help figure it out. 

Here is my first try at a Dockerfile

```
# Pull base image.
FROM node:16-buster

# Install desired stuff
RUN cd /opt && \
    git clone https://github.com/vantezzen/blymp-io && \
    cd /opt/blymp-io && \
    npm install && \
    npm run build && \
    npm start

```

First build errors:

```
Cloning into 'blymp-io'...
npm notice
npm notice New minor version of npm available! 7.15.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: blymp-io@1.0.0
npm ERR! Found: webpack@5.42.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^3.0.0 || ^4.0.0" from url-loader@1.1.2
npm ERR! node_modules/url-loader
npm ERR!   dev url-loader@"^1.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-02T15_52_42_568Z-debug.log
```
any hints please?

**Comment by vantezzen** [comment]
Can reproduce this using the repo. It looks like url-loader is using the wrong version for webpack. I just commited https://github.com/vantezzen/blymp-io/commit/f514e84120a69b9056160c32e6c7682717651659 which seems to solve this problem for me. Can you try again?

**Comment by ovizii** [comment]
Thanks for the prompt reaction and the delay on my side. I just tried again and its stuck at this step for the last 30 minutes :-( 

I guess I'll have to google and see what is happening here. Will reply to this post once I have figured something out.

```
docker build -t blymp-io .
Sending build context to Docker daemon  4.608kB
Step 1/2 : FROM node:16-buster
 ---> f3b84aa4bb3d
Step 2/2 : RUN cd /opt &&     git clone https://github.com/vantezzen/blymp-io &&     cd /opt/blymp-io &&     npm install &&     npm run build &&     npm start
 ---> Running in 02842af3b025
Cloning into 'blymp-io'...

```

**Comment by ovizii** [comment]
ok, the cloning eventually continued, the next steps of install and build gave some deprecation and notice warnings. Will follow up once I have figured out how to proceed now that I have build the image.

**Comment by ovizii** [comment]
Sorted. There was a problem "git clone" was hanging at: "POST git-upload-pack (227 bytes)" 

but eventually finished. All working now. If you want, you can give me some hints on how I can customize the front page but its not necessary as this is simply for my own usage so I don't mind it looking exactly like https://blym.io :-) 

Btw. here is the latest Dockerfile I used:


```
# Pull base image.
FROM node:16-buster

# Install desired stuff
RUN cd /opt && \
    git clone --verbose https://github.com/vantezzen/blymp-io && \
    cd /opt/blymp-io && \
    npm install && \
    npm run build

WORKDIR /opt/blymp-io

ENTRYPOINT ["npm", "start"]

```

if anyone's interested here is my docker-compose.yml

```
version: '2.2'

services:

# https://github.com/vantezzen/blymp-io
    blymp:
        build: .
        image: blymp-io
        container_name: blymp
        hostname: blymp
        restart: "no"

        ports:
          - 5805:8080

        networks:
             - sharing

networks:
    sharing:
        external:
            name: sharing

```

**Comment by vantezzen** [comment]
Thank you for your response. I will add your Docker files to the repo, so others can see them there.

As for customization, blymp doesn't have any easy switches to change the design but most css is contained in `src/client/app.css` and `src/client/pages/home.css` if you want to edit that, the HTML part of the homepage is contained in `src/client/pages/home.tsx`.
