### ISSUE TITLE
Button to start transfer is invisible on light-mode

### ISSUE THREAD

**Issue by zznidar** [vantezzen/blymp-io#7]
Once a file is selected, the button to start transfer disappears (actually, it still exists, but background is transparent and text colour is almost the same as background elements – contrast is 1.01).

This only seems to be an issue on light-mode. If your device is set to dark-mode, the appearance is different and the button is well visible.

![image](https://user-images.githubusercontent.com/20877556/186173200-a0522db3-d67c-47ab-ad7e-6d5b7e81b329.png)

**Comment by vantezzen** [comment]
Thank you for the bug report! Looks like some styles got overridden there - it should be fixed now
